# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenflow" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "b1143b545c6234af1bb147111f17d33345a94243942e50adc3060a71692f93b6"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7e09f13137856e2ca735b4220e7f00824618eba060205ccfa7c70225ca4354f0"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "381565b23810e5ab10c016f414c6448b6b9b747808bd92a0e2062212115f5526"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9024a24991ce3d2bb1f8d57d86648743c976471f27069dcf9222681a6e69ebb7"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zenflow"
  desc "Declarative multi-agent workflows with first-class messaging"
  homepage "https://zenflow.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zenflow"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zenflow"]
  end

  # No zap stanza required

  caveats <<~EOS
    Licensed under Apache-2.0. https://github.com/zendev-sh/zenflow/blob/main/LICENSE
    zenflow is not yet Apple-notarised. The post-install hook strips
    the macOS quarantine attribute so Gatekeeper does not block
    first-run; if you reinstall manually, run:
      xattr -dr com.apple.quarantine $(brew --prefix)/bin/zenflow
  EOS
end
