# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenflow" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e59ccfd8959112dc7edfbfca25ed313bf5330cda61f26b2accf54c3210caeebe"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1669f5ec353d077cd19aecbda0273cc093604acca4c6ade507c6e25ab663f6e4"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "971cf48bc329eaab98ec09f4d597196fdc7be1260262dc2a8bea702e8901dd8b"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6bf9af391b29f93b6665205ff4f847ce6bd9d07e6732f8665ec6d3eb3f09f896"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zenflow"
  desc "Declarative multi-agent workflows with first-class messaging"
  homepage "https://zenflow.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zenflow"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zenflow"]
  end

  # No zap stanza required

  caveats <<~EOS
    Licensed under Apache-2.0. https://github.com/zendev-sh/zenflow/blob/main/LICENSE
    zenflow is not yet Apple-notarised. The post-install hook strips
    the macOS quarantine attribute so Gatekeeper does not block
    first-run; if you reinstall manually, run:
      xattr -dr com.apple.quarantine $(brew --prefix)/bin/zenflow
  EOS
end
