# This file was generated by GoReleaser. DO NOT EDIT.
cask "zenflow" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "2d828633d19382342bcb902656df8c0196b55827ccb0c3d12998c7c56339c79d"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d81942812f09394180ada5674b17ee9494c383cea1efc51c8a1dad037c3c442a"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4a50fa4b87661933c8850397115eaae77944143de4714d04b7c3e363ba4d2ea"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "50f9324165337e2a6a3f937b696fda003281ac802cdf12544c2951c813e8f370"
      url "https://github.com/zendev-sh/zenflow/releases/download/v#{version}/zenflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zenflow"
  desc "Declarative multi-agent workflows with first-class messaging"
  homepage "https://zenflow.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zenflow"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zenflow"]
  end

  # No zap stanza required

  caveats <<~EOS
    Licensed under Apache-2.0. https://github.com/zendev-sh/zenflow/blob/main/LICENSE
    zenflow is not yet Apple-notarised. The post-install hook strips
    the macOS quarantine attribute so Gatekeeper does not block
    first-run; if you reinstall manually, run:
      xattr -dr com.apple.quarantine $(brew --prefix)/bin/zenflow
  EOS
end
